#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

#
# Dockerfile for guacamole-server
#

FROM ruby:2.3-slim
MAINTAINER TrueAbility Ops <ops@trueability.com>

# Environment variables
ENV \
    BUILD_DIR=/tmp/guacd-docker-BUILD \
    LC_ALL=en_US.UTF-8                \
    LANGUAGE=en_US                    \
    LANG=en_US                        \
    RUNTIME_DEPENDENCIES="            \
        locales                       \
        libcairo2                     \
        fonts-dejavu                  \
        freerdp-x11                   \
        libfreerdp-common1.1.0        \
        libfreerdp-plugins-standard   \
        ghostscript                   \
        libjpeg62-turbo               \
        libssh2-1                     \
        fonts-liberation              \
        libtelnet2                    \
        libvorbis0a                   \
        libvncserver0                 \
        libwebp5                      \
        libpango-1.0.0                \
        xfonts-terminus               \
        ffmpeg                        \
        libossp-uuid16                \
        libavutil55                   \
        libswscale4"                  \
    BUILD_DEPENDENCIES="              \
        autoconf                      \
        automake                      \
        libcairo2-dev                 \
        libfreerdp-dev                \
        gcc                           \
        libjpeg62-turbo-dev           \
        libssh2-1-dev                 \
        libtool                       \
        libtelnet-dev                 \
        libvorbis-dev                 \
        libvncserver-dev              \
        libwebp-dev                   \
        make                          \
        libpango1.0-dev               \
        libossp-uuid-dev              \
        libavcodec-dev                \
        libavutil-dev                 \
        libswscale-dev"


# Bring environment up-to-date and install guacamole-server dependencies
RUN echo "deb http://ftp.uk.debian.org/debian jessie-backports main" >> /etc/apt/sources.list && \
    apt-get -y update  && \
    apt-get -y upgrade && \
    apt-get -y install $RUNTIME_DEPENDENCIES && \
    apt-get -y clean all

# Add configuration scripts
COPY src/guacd-docker/bin /opt/guacd/bin/

# Copy source to container for sake of build
COPY . "$BUILD_DIR"

# Overwrite Upstream build script
COPY ./ta-web-build.sh /opt/guacd/bin/build-guacd.sh

# Build guacamole-server from local source
RUN apt-get -y install $BUILD_DEPENDENCIES         && \
    echo en_US UTF-8 >> /etc/locale.gen            && \
    locale-gen en_US.UTF-8                         && \
    /opt/guacd/bin/build-guacd.sh "$BUILD_DIR"     && \
    rm -Rf "$BUILD_DIR"                            && \
    apt-get -y autoremove $BUILD_DEPENDENCIES      && \
    apt-get -y clean all

# Start guacd, listening on port 0.0.0.0:4822
# EXPOSE 4822
# CMD [ "/usr/local/sbin/guacd", "-b", "0.0.0.0", "-f" ]
